"""Initial migration

Revision ID: 340143fe277b
Revises: 
Create Date: 2024-12-01 07:21:30.162741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340143fe277b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('artist_id', sa.String(length=80), nullable=False),
    sa.Column('artist_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('artist_id')
    )
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artist_artist_name'), ['artist_name'], unique=True)

    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('preferred_artists', sa.String(length=200), nullable=True),
    sa.Column('preferred_genres', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('album',
    sa.Column('album_id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('artist_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.artist_id'], ),
    sa.PrimaryKeyConstraint('album_id')
    )
    op.create_table('chat',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('playlist',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('playlist_id')
    )
    op.create_table('song',
    sa.Column('song_id', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=80), nullable=True),
    sa.Column('album_id', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.album_id'], ),
    sa.PrimaryKeyConstraint('song_id')
    )
    op.create_table('playlist_song',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.playlist_id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.song_id'], ),
    sa.PrimaryKeyConstraint('playlist_id', 'song_id')
    )
    op.create_table('song_artist',
    sa.Column('song_id', sa.String(length=80), nullable=False),
    sa.Column('artist_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.artist_id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.song_id'], ),
    sa.PrimaryKeyConstraint('song_id', 'artist_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song_artist')
    op.drop_table('playlist_song')
    op.drop_table('song')
    op.drop_table('playlist')
    op.drop_table('chat')
    op.drop_table('album')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artist_artist_name'))

    op.drop_table('artist')
    # ### end Alembic commands ###
